apiVersion: v1
kind: Service
metadata:
  name: {{ include "tasktracker.fullname" . }}-frontend
  labels:
    {{- include "tasktracker.labels" . | nindent 4 }}
    tier: frontend
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "tasktracker.selectorLabels" . | nindent 4 }}
    tier: frontend