{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tasktracker.fullname" . }}-ingress
  labels:
    {{- include "tasktracker.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.frontend.host | quote }}
      http:
        paths:
          # Route API and Auth requests to the backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "tasktracker.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "tasktracker.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          # Route all other requests to the frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tasktracker.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.frontend.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
